name: Pipeline Backend
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Pylint
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pylint $(find . -name "*.py" | xargs)
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Pytest
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run pytest `ls -R|grep test_*.py$|xargs`
